// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMws1oqbMauL8_qczixtTyUCdmpvnPgFs',
    appId: '1:708277942716:web:d9d4d0dc399af3958d93b9',
    messagingSenderId: '708277942716',
    projectId: 'nastefoodwo',
    authDomain: 'nastefoodwo.firebaseapp.com',
    storageBucket: 'nastefoodwo.firebasestorage.app',
    measurementId: 'G-4WFR7KY8L2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmLg87n3oJRASg_SYrLOM3EeG9Zw1OJ3U',
    appId: '1:708277942716:android:df59d6d6f8b544ff8d93b9',
    messagingSenderId: '708277942716',
    projectId: 'nastefoodwo',
    storageBucket: 'nastefoodwo.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOLbVaMwjbG0hG5bauN0e1EbRALTAfb7Q',
    appId: '1:708277942716:ios:ee02a4fed77ce7718d93b9',
    messagingSenderId: '708277942716',
    projectId: 'nastefoodwo',
    storageBucket: 'nastefoodwo.firebasestorage.app',
    iosBundleId: 'com.example.nastefoodwo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOLbVaMwjbG0hG5bauN0e1EbRALTAfb7Q',
    appId: '1:708277942716:ios:ee02a4fed77ce7718d93b9',
    messagingSenderId: '708277942716',
    projectId: 'nastefoodwo',
    storageBucket: 'nastefoodwo.firebasestorage.app',
    iosBundleId: 'com.example.nastefoodwo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMws1oqbMauL8_qczixtTyUCdmpvnPgFs',
    appId: '1:708277942716:web:be4d9d74f9a670468d93b9',
    messagingSenderId: '708277942716',
    projectId: 'nastefoodwo',
    authDomain: 'nastefoodwo.firebaseapp.com',
    storageBucket: 'nastefoodwo.firebasestorage.app',
    measurementId: 'G-LCS2Q1QCSF',
  );
}
